-- Mejora de la nota corta «Cómo automatizar tus reportes de marketing y ahorrar horas cada mes»
-- Corrige: «Google Data Studio» (hoy Looker Studio), promesa de tiempo real y herramientas genéricas;
-- agrega frecuencias de actualización reales (documentación de Looker Studio, sept 2026).

-- 1) Ejecutar ahora:
update articulos set
resumen = $r$Tres formas de automatizar tus reportes de marketing (envío programado, datos consolidados y flujos con alertas) y qué frecuencia de actualización esperar de cada fuente.$r$,
contenido = $c$<h2>Por qué automatizar tus reportes</h2><p>Armar el reporte mensual a mano significa entrar a cada plataforma, exportar cifras, pegarlas en una hoja y enviar un PDF que ya llega desactualizado. Casi nada de eso requiere criterio: es transporte de datos. Automatizarlo libera horas y, sobre todo, hace que las cifras lleguen a tiempo para corregir el gasto o el mensaje antes de que termine el mes.</p><h2>Tres niveles, del más simple al más completo</h2><ul><li><strong>Envío programado:</strong> Looker Studio puede enviar un tablero por correo con la frecuencia que definas (Compartir → Programar entrega). El mensaje lleva un PDF, una vista previa de la primera página y un enlace al reporte, con hasta 50 destinatarios.</li><li><strong>Datos consolidados:</strong> las cifras de tus plataformas llegan solas a una hoja o base de datos, y el reporte se construye sobre esa fuente única.</li><li><strong>Flujo con alertas:</strong> una herramienta de flujos, como n8n, revisa los datos según un horario, compara contra tus metas y avisa cuando algo sale de rango.</li></ul><h2>Qué frecuencia de actualización esperar</h2><p>No prometas «tiempo real». En Looker Studio, los productos de marketing de Google (Google Ads, Google Analytics, Search Console) se actualizan cada 12 horas; Google Sheets, cada 15 minutos por defecto; y BigQuery es configurable entre 1 minuto y 12 horas. Indica siempre la fecha y hora de corte en el reporte.</p><h2>Cómo implementarlo paso a paso</h2><ul><li><strong>Define las decisiones:</strong> qué revisas cada semana y qué te haría actuar.</li><li><strong>Elige de 5 a 8 indicadores</strong> con fórmula y fuente documentadas.</li><li><strong>Consolida y valida:</strong> compara al menos tres cifras contra la plataforma de origen.</li><li><strong>Programa el envío</strong> por audiencia: dirección necesita pocos indicadores; operación, el detalle.</li><li><strong>Agrega alertas</strong> solo para lo que exige acción rápida y revisa el reporte cada trimestre.</li></ul><h2>Errores comunes</h2><ul><li>Automatizar un reporte enorme que nadie lee.</li><li>Elegir herramientas que no se conectan con tus fuentes y terminar copiando datos a mano.</li><li>No tener un responsable: cuando cambia una conexión, el envío falla y nadie se entera.</li></ul><h2>Cierre</h2><p>Empieza por lo más simple: un tablero con envío programado y una definición clara de qué decisiones apoya. Después suma datos consolidados y alertas cuando el volumen lo justifique.</p>$c$
where slug = 'automatizar-reportes-marketing-260919';

-- 2) Ejecutar SOLO después de publicar (push) el artículo completo, para que el enlace no dé 404:
update articulos set contenido = contenido || $l$<p class="articulo-completo"><strong>Análisis completo:</strong> <a href="/blog/automatizar-reportes-de-marketing/">Cómo automatizar tus reportes de marketing y ahorrar horas cada mes →</a></p>$l$
where slug = 'automatizar-reportes-marketing-260919'
  and contenido not like '%articulo-completo%';

-- Reversa: el contenido original está guardado en la sesión de trabajo; pide restaurarlo si hace falta.
