-- Enlace «Análisis completo» al final de cada nota corta de Supabase.
-- Ejecutar DESPUÉS de publicar (push) el sitio, para que los enlaces no den 404. Es idempotente (no duplica el bloque).

update articulos set contenido = contenido || $l$<p class="articulo-completo"><strong>Análisis completo:</strong> <a href="/blog/contenido-ia-menores-fallo-septimo-circuito/">Contenido con IA y menores: qué dijo el fallo del Séptimo Circuito y qué debe hacer tu marca →</a></p>$l$ where slug = 'decision-judicial-csam-marketing-digital' and contenido not like '%articulo-completo%';
update articulos set contenido = contenido || $l$<p class="articulo-completo"><strong>Análisis completo:</strong> <a href="/blog/pinterest-nvidia-busqueda-visual-ia/">Pinterest y Nvidia: qué significa la nueva capa de IA para el descubrimiento y las compras →</a></p>$l$ where slug = 'pinterest-nvidia-alianza-potenciar-descubrimiento-ai' and contenido not like '%articulo-completo%';
update articulos set contenido = contenido || $l$<p class="articulo-completo"><strong>Análisis completo:</strong> <a href="/blog/gafas-ia-meta-herramientas-creacion-instagram/">Gafas con IA de Meta: qué herramientas de creación llegan a Instagram y cómo probarlas →</a></p>$l$ where slug = 'nuevas-herramientas-creacion-gafas-ia-meta' and contenido not like '%articulo-completo%';
update articulos set contenido = contenido || $l$<p class="articulo-completo"><strong>Análisis completo:</strong> <a href="/blog/visor-realidad-mixta-meta-phoenix/">Visor de realidad mixta de Meta (Project Phoenix): qué se reporta y cómo prepararte sin arriesgar presupuesto →</a></p>$l$ where slug = 'meta-nuevo-dispositivo-realidad-virtual' and contenido not like '%articulo-completo%';
update articulos set contenido = contenido || $l$<p class="articulo-completo"><strong>Análisis completo:</strong> <a href="/blog/threads-vs-x-audiencia-marcas/">Threads vs X: qué dijo Zuckerberg y cómo decidir en cuál publicar tu marca →</a></p>$l$ where slug = 'threads-meta-superar-x' and contenido not like '%articulo-completo%';
update articulos set contenido = contenido || $l$<p class="articulo-completo"><strong>Análisis completo:</strong> <a href="/blog/youtube-cultura-mainstream-microtendencias/">YouTube y la cultura compartida: qué dice «In Search of Mainstream» para tu contenido →</a></p>$l$ where slug = 'influencia-youtube-cultura-popular' and contenido not like '%articulo-completo%';
update articulos set contenido = contenido || $l$<p class="articulo-completo"><strong>Análisis completo:</strong> <a href="/blog/google-data-manager-datos-propios/">Google Data Manager: qué anunció y cómo preparar tus datos propios para tus campañas →</a></p>$l$ where slug = 'mejoras-plataforma-data-manager-google' and contenido not like '%articulo-completo%';
update articulos set contenido = contenido || $l$<p class="articulo-completo"><strong>Análisis completo:</strong> <a href="/blog/tiktok-mes-herencia-hispana-marcas/">TikTok y el Mes de la Herencia Hispana: cómo participar con criterio →</a></p>$l$ where slug = 'tiktok-celebra-mes-herencia-hispana' and contenido not like '%articulo-completo%';
update articulos set contenido = contenido || $l$<p class="articulo-completo"><strong>Análisis completo:</strong> <a href="/blog/x-cashtags-trading-redes-sociales/">X Cashtags: qué es realmente la función de trading y qué puede aprender tu marca →</a></p>$l$ where slug = 'x-incorpora-comercio-acciones' and contenido not like '%articulo-completo%';
update articulos set contenido = contenido || $l$<p class="articulo-completo"><strong>Análisis completo:</strong> <a href="/blog/x-cashtags-trading-redes-sociales/">X Cashtags: qué es realmente la función de trading y qué puede aprender tu marca →</a></p>$l$ where slug = 'x-incorpora-trading-acciones' and contenido not like '%articulo-completo%';
update articulos set contenido = contenido || $l$<p class="articulo-completo"><strong>Análisis completo:</strong> <a href="/blog/colaboraciones-creadores-instagram-emplifi/">Colaboraciones con creadores en Instagram: qué dice el estudio de Emplifi y cómo probarlas →</a></p>$l$ where slug = 'colaboraciones-creadores-instagram' and contenido not like '%articulo-completo%';
update articulos set contenido = contenido || $l$<p class="articulo-completo"><strong>Análisis completo:</strong> <a href="/blog/colaboraciones-creadores-instagram-emplifi/">Colaboraciones con creadores en Instagram: qué dice el estudio de Emplifi y cómo probarlas →</a></p>$l$ where slug = 'colaboraciones-creadores-instagram-260919' and contenido not like '%articulo-completo%';
update articulos set contenido = contenido || $l$<p class="articulo-completo"><strong>Análisis completo:</strong> <a href="/blog/facebook-limite-enlaces-meta-one/">Facebook limita los enlaces en páginas: qué está confirmado y cómo ajustar tu estrategia →</a></p>$l$ where slug = 'facebook-pages-limita-publicaciones-enlaces' and contenido not like '%articulo-completo%';
update articulos set contenido = contenido || $l$<p class="articulo-completo"><strong>Análisis completo:</strong> <a href="/blog/meta-business-agent-whatsapp/">Meta Business Agent en WhatsApp: qué hace, cómo configurarlo y qué vigilar →</a></p>$l$ where slug = 'mejora-atencion-clientes-whatsapp' and contenido not like '%articulo-completo%';
update articulos set contenido = contenido || $l$<p class="articulo-completo"><strong>Análisis completo:</strong> <a href="/blog/meta-business-agent-whatsapp/">Meta Business Agent en WhatsApp: qué hace, cómo configurarlo y qué vigilar →</a></p>$l$ where slug = 'facilita-atencion-cliente-ia-whatsapp' and contenido not like '%articulo-completo%';
update articulos set contenido = contenido || $l$<p class="articulo-completo"><strong>Análisis completo:</strong> <a href="/blog/linkedin-ads-segmentacion-audiencia/">LinkedIn Ads: cómo segmentar tu audiencia según las recomendaciones oficiales →</a></p>$l$ where slug = 'mejorar-segmentacion-empresa-linkedin-260919' and contenido not like '%articulo-completo%';
update articulos set contenido = contenido || $l$<p class="articulo-completo"><strong>Análisis completo:</strong> <a href="/blog/meta-festividades-2026-plan/">Festividades 2026: qué publicó Meta y cómo planificar tu temporada hacia atrás →</a></p>$l$ where slug = 'guia-planificacion-festividades-2026-meta-260919' and contenido not like '%articulo-completo%';
update articulos set contenido = contenido || $l$<p class="articulo-completo"><strong>Análisis completo:</strong> <a href="/blog/reddit-festividades-2026-guia/">Reddit y las festividades 2026: qué dice su guía para pymes y cuándo participar →</a></p>$l$ where slug = 'guia-reddit-planificacion-ventas-260919' and contenido not like '%articulo-completo%';

-- Corrección recomendada de la nota «decision-judicial-csam-marketing-digital»:
-- afirma que «la corte dictaminó que puede ser legal» generar imágenes de menores con IA. Eso es inexacto:
-- el tribunal resolvió solo sobre la posesión privada en el hogar de cierto material sin niño real, y no legalizó su creación ni distribución.
update articulos set
resumen = $r$Qué resolvió realmente un tribunal de EE. UU. sobre material generado con IA, por qué no es un permiso para nadie y qué controles debe tener tu equipo de marketing.$r$,
contenido = $c$<h2>Qué se resolvió</h2><p>El 25 de agosto de 2026, el Tribunal de Apelaciones del Séptimo Circuito de EE. UU. resolvió que el gobierno no podía sancionar penalmente la posesión privada, en el hogar, de cierto material obsceno generado por IA en el que no aparece un niño real. El fallo no legaliza crear ni distribuir ese material, y aplica solo dentro de ese circuito.</p><h2>Qué significa para una marca</h2><p>Ninguna. Las plataformas prohíben este tipo de contenido en sus políticas, la legislación de cada país es distinta y el riesgo reputacional no depende de la ley. Si tu equipo usa IA generativa, define una política de contenido, revisa las imágenes con personas antes de publicar y pide a tus proveedores cumplimiento de políticas.</p>$c$
where slug = 'decision-judicial-csam-marketing-digital';
